### ISSUE TITLE
cli:ressources requises au total pour faire les 8 incantations en une fois

### ISSUE THREAD

**Issue by LinFeiLong** [gbersac/zappy_42#11]
linemate: 9
deraumere: 8
sibur: 10
mendiane: 5
phiras: 6
thystame: 1

**Comment by gbersac** [comment]
Je ne sais pas exactement à quoi tu fais référence, mais si c'est pour les ressources néscessaires pour démarer une incantation, ne t'embéte pas à réimplémenter tout cela, je l'ai déjà fait :  https://github.com/gbersac/zappy_42/blob/master/ser/inc/incantation.h

Il suffit que tu transfert ce .h et toutes les fonctions associées dans le dossier gen/

**Comment by LinFeiLong** [comment]
j'ai modifié le titre

**Comment by gbersac** [comment]
Ok, je vois ce que tu veux faire. Malin ! Note que seul le trantor qui lance l'incantation a besoin d'avoir les ressources néscessaire au lancement de l'incantation. De plus il faut lancer 6 incantation de niveau 1 pour avoir 6 trantor au niveau 7 pour lancer l'incantation finale, 3 de niveau 2...au final je crois que c'est plus que cela qui est nécessaire.
