### ISSUE TITLE
cli:Incantion, que font les trantors?

### ISSUE THREAD

**Issue by LinFeiLong** [gbersac/zappy_42#13]
Pendant l'incatation, seul l'invocateur est imobilisé ou tous les trantors faisant l'incantation sont immobilisés?

**Comment by gbersac** [comment]
Non, tout les trantors inpliqués dans l'incantation sont immobilisé (countdown up de [CMD_INCANTATION_TIME](https://github.com/gbersac/zappy_42/blob/master/ser/inc/cmd.h#L39). ENcore une fois, n'hésite pas à transférer ce qui pourrait t'être utile dans ser vers gen.

**Comment by LinFeiLong** [comment]
ok bon a savoir.
