### ISSUE TITLE
Cli: incantation: reponse

### ISSUE THREAD

**Issue by LinFeiLong** [gbersac/zappy_42#15]
pour la reponse del'incantation. 
C'est en deux temps?
1. elevation en cours a 0/t
2. niveau actuel : K a 300/t

C'est ca?

**Comment by gbersac** [comment]
Il n'y a pas de réponse. Que le retour ok lorsque tu lance l'incantation. A partir de ce moment là, tu es certain que l'incantation ira jusqu'au bout.

**Comment by LinFeiLong** [comment]
Oki nickel

**Comment by mdebelle** [comment]
et le graphic il reçoit quoi ??
