### ISSUE TITLE
cli: broadcast: reponse

### ISSUE THREAD

**Issue by LinFeiLong** [gbersac/zappy_42#16]
je propose selon ce qui a ete fait;

boradcast, <direction_du_son>, <string>

**Comment by gbersac** [comment]
c'est déjà le cas, en plus il y a position (x, y) et team. https://github.com/gbersac/zappy_42/blob/master/ser/src/cli/ser_broadcast.c#L12-L18

**Comment by LinFeiLong** [comment]
ah bah nickel
