### ISSUE TITLE
serveur->player commands

### ISSUE THREAD

**Issue by gbersac** [gbersac/zappy_42#3]
- [x] avance
- [x] broadcast
- [x] droite
- [x] gauche
- [x] voir
- [x] inventaire
- [x] prend
- [x] pose
- [x] expulse
- [x] incantation
- [x] newturn
- [x] begin_info
- [x] fork
- [x] connect_nbr
- [x] mort
- [x] déplacement : lorsqu'un joueur se fait expulser, il reçoit cette commande pour en être informé.

**Comment by LinFeiLong** [comment]
je comprends pas comment fonctionne prend et pose?
Je suis sensé mettre quoi?

**Comment by gbersac** [comment]
Prend nom_pierre
Pose nom_pierre

Check sur ser_prend sinon pour voir comment il marche‎.

Envoyé de mon smartphone BlackBerry 10 sur le réseau Orange.
De: LinFeiLong
Envoyé: mercredi 30 décembre 2015 20:23
À: gbersac/zappy_42
Répondre à: gbersac/zappy_42
Cc: Guillaume Bersac
Objet: Re: [zappy_42] serveur->player commands (#3)

je comprends pas comment fonctionne prend et pose?
Je suis sensé mettre quoi?

---

**Comment by LinFeiLong** [comment]
Oki, my bad. Ca marche nickel!!!

**Comment by gbersac** [comment]
Amazing !

Envoyé de mon smartphone BlackBerry 10 sur le réseau Orange.
De: LinFeiLong
Envoyé: samedi 2 janvier 2016 02:34
À: gbersac/zappy_42
Répondre à: gbersac/zappy_42
Cc: Guillaume Bersac
Objet: Re: [zappy_42] serveur->player commands (#3)

Oki, my bad. Ca marche nickel!!!

---
