### ISSUE TITLE
Egg ready and new player

### ISSUE THREAD

**Issue by jcoignet** [gbersac/zappy_42#44]
When an egg is ready, if a new player connects it doesn't send "ebo #e" and player popped with pnw is not at the egg location.

**Comment by gbersac** [comment]
Ce n'est pas une erreur. Le système d'oeuf fonctionne bien, c'est juste que le joueur ne prendra un oeuf que si tout les slot de connection initiaux sont déjà utilisé. Or, il reste un slot de libre lors du premier oeuf pondu.
