### ISSUE TITLE
client/serveur no more than 10 request without response

### ISSUE THREAD

**Issue by gbersac** [gbersac/zappy_42#5]

**Comment by LinFeiLong** [comment]
Je peux envoyer plusieurs requests à la fois????
Ou je dois attendre le retour apres chaque requete?

**Comment by gbersac** [comment]
Tu vas avoir du mal à savoir à quoi correspond une réponses si tu envoies plusieurs requêtes en même temps car tu auras plusieurs réponses en même temps.

Envoyé de mon smartphone BlackBerry 10 sur le réseau Orange.
De: LinFeiLong
Envoyé: mardi 29 décembre 2015 23:20
À: gbersac/zappy_42
Répondre à: gbersac/zappy_42
Cc: Guillaume Bersac
Objet: Re: [zappy_42] client/serveur no more than 10 request without response (#5)

Je peux envoyer plusieurs requests à la fois????
Ou je dois attendre le retour apres chaque requete?

---

**Comment by LinFeiLong** [comment]
Je suis d'accord, mais je suis qd meme sense les recevoirs dans l'ordre non?

**Comment by gbersac** [comment]
C'est vrai. Fait comme si toutes les requêtes étaient bien arrivées sinon.

Envoyé de mon smartphone BlackBerry 10 sur le réseau Orange.
De: LinFeiLong
Envoyé: mercredi 30 décembre 2015 10:15
À: gbersac/zappy_42
Répondre à: gbersac/zappy_42
Cc: Guillaume Bersac
Objet: Re: [zappy_42] client/serveur no more than 10 request without response (#5)

Je suis d'accord, mais je suis qd meme sense les recevoirs dans l'ordre non?

---

**Comment by gbersac** [comment]
Ce cas ne s'est jamais présenteé en test, il n'est donc pas géré
