### ISSUE TITLE
serveur->gfx commands

### ISSUE THREAD

**Issue by gbersac** [gbersac/zappy_42#6]
- [x] msz : Taille de la carte.
- [x] bct : Contenu d’une case de la carte.
- [x] mct : Contenu de la carte (toutes les cases).
- [x] tna : Nom des équipes.
- [x] ppo : Position d’un joueur.
- [x] plv : Niveau d’un joueur.
- [x] pin : Inventaire d’un joueur.
- [x] pex : Un joueur expulse.
- [x] pbc : Un joueur fait un broadcast.
- [x] pic : Premier joueur lance l’incantation pour tous les suivants sur la case.
-  pie : Fin de l’incantation sur la case donneé avec le résultat R (0 ou 1). NOT IMPLEMENTED !
- [x] pfk : Le joueur pond un œuf.
- [x] pdr : Le joueur jette une ressource.
- [x] pgt : Le joueur prend une ressource.
- [x] pdi : Le joueur est mort de faim.
- [x] enw : L’œuf a été pondu sur la case par le joueur.
- [x] eht! : L’œuf éclot.
- [x] ebo! : Un joueur s’est connecté pour l’œuf.
- edi : L’œuf éclos est mort de faim.  NOT IMPLEMENTED !
- [x] sgt : Demande de l’unité de temps courante sur le serveur.
-  [x] sst : Modification de l’unité de temps sur le serveur.
- [x] seg : Fin du jeu. L’équipe donneé remporte la partie.
- [ ] smg : Message du serveur.
- [x] suc : Commande inconnue.
- [ ] sbp : Mauvais paramètres pour la commande.

**Comment by mdebelle** [comment]
suggestion pour la commande "sst _nb_"

```
int     gfx_sst(t_env *env, t_fd *fd, char *cmd)
{
    char    *to_send;

    env->map.time_d = ft_atoi(ft_strrchr(cmd, ' '));
    to_send = (char*)malloc(4);
    asprintf(&to_send, "sgt %d\n", env->map.time_d);
    send_cmd_to_client(fd, to_send);
    return (1);
}
```
