### ISSUE TITLE
ser: eating

### ISSUE THREAD

**Issue by gbersac** [gbersac/zappy_42#9]

**Comment by LinFeiLong** [comment]
Est-ce que la nourriture est automatiquement absorbe lors de la prise de nourriture depuis le sol?
Si oui, la nourriture ne devrait pas pouvoir être stockées dans l'inventaire.

**Comment by gbersac** [comment]
Oui, elle est absorbée lors du ramassage.

Envoyé de mon smartphone BlackBerry 10 sur le réseau Orange.
De: LinFeiLong
Envoyé: lundi 7 décembre 2015 09:10
À: gbersac/zappy_42
Répondre à: gbersac/zappy_42
Cc: Guillaume Bersac
Objet: Re: [zappy_42] ser: eating (#9)

Est-ce que la nourriture est automatiquement absorbe lors de la prise de nourriture depuis le sol?
Si oui, la nourriture ne devrait pas pouvoir être stockées dans l'inventaire.

---

**Comment by LinFeiLong** [comment]
Tiens je viens de voir un truc page 10.

III.9 Inventaire
Cette commandes permet de voir ce que le drone a comme objet et combien de temps
il lui reste a vivre. Le seveur enverra par exemple la ligne suivante :
{nourriture 345, sibur 3, phiras 5, ..., deraumere 0}

Donc ok, la nourriture est assimile mais elle peut etre retire.
Autre point du coup pas besoin de timing cote client.

Donc inventaire pourrait renvoyer
{nourriture 345, (point_de_vie_total_avec_nourriture), ... }.

**Comment by gbersac** [comment]
Note déjà que c'est ainsi que sera la commande `ìnventaire %d %d %d %d %d %d %d`. Ensuite, pourquoi pas rajouter les points de vie à la fin.

**Comment by LinFeiLong** [comment]
c parfait merci
